import { defineConfig } from 'vitest/config';

export default defineConfig({
    test: {
        globals: true,
        environment: 'jsdom',
        setupFiles: ['./tests/setup.js'],
        exclude: [
            '**/node_modules/**',
            '**/dist/**',
            '**/e2e/**',
            '**/tests/archive/**',
            '**/*.spec.js',
            '**/validate-duckdb-aggregations.test.js',
            '**/duckdb-enforcement.test.js',
            '**/validate-json-baseline.test.js',
            '**/data-quality-monitor.test.js',
            '**/validate-overview-page.test.js',
            '**/validate-prediction-page.test.js',
            '**/validate-themes-page.test.js',
            '**/validate-mechanics-page.test.js',
            '**/validate-providers-page.test.js',
            '**/validate-insights-page.test.js',
            '**/validate-anomalies-page.test.js',
            '**/validate-games-page.test.js',
            '**/validate-trends-page.test.js',
            '**/validate-ai-assistant-page.test.js',
            '**/validate-ui-rendering-bugs.test.js',
            '**/theme-clickability.test.js',
            '**/filters-comprehensive.test.js',
        ],
        coverage: {
            provider: 'v8',
            reporter: ['text-summary', 'json-summary', 'json', 'html'],
            include: [
                'src/lib/filters.js',
                'src/lib/auth.js',
                'src/lib/env.js',
                'src/lib/game-analytics-engine.js',
                'src/lib/sanitize.js',
                'src/lib/symbol-utils.js',
                'src/lib/features.js',
                'src/lib/shared-config.js',
                'src/lib/game-fields.js',
                'src/lib/metrics.js',
                'src/lib/parse-features.js',
                'src/config/mechanics.js',
            ],
            exclude: ['node_modules/', 'tests/', 'dist/', 'scripts/', '**/*.config.js'],
            thresholds: {
                lines: 40,
                functions: 70,
                branches: 70,
                statements: 40,
            },
        },
        testTimeout: 15000,
        hookTimeout: 30000,
        sequence: {
            setupFiles: 'list',
        },
        pool: 'forks',
        fileParallelism: true,
    },
    resolve: {
        alias: {
            '@': '/src',
        },
    },
});
