/**
 * Official provider websites for dashboard links.
 * Merged from data/enrich_websearch.py PROVIDER_WEBSITES plus verified top-provider URLs.
 */
export const PROVIDER_URLS = {
    'Light & Wonder': 'https://www.lnw.com',
    AGS: 'https://www.playags.com',
    Evolution: 'https://www.evolution.com',
    IGT: 'https://www.igt.com',
    Playtech: 'https://www.playtech.com',
    'Games Global': 'https://www.gamesglobal.com',
    Everi: 'https://www.everi.com',
    Aristocrat: 'https://www.aristocrat.com',
    'High 5 Games': 'https://www.high5games.com',
    Greentube: 'https://www.greentube.com',
    Konami: 'https://www.konami.com/gaming',
    'Gaming Realms': 'https://www.gamingrealms.com',
    'Hacksaw Gaming': 'https://www.hacksawgaming.com',
    "Play'n GO": 'https://www.playngo.com',
    Wazdan: 'https://www.wazdan.com',
    'Bragg Gaming Group': 'https://www.bragg.games',
    'Blueprint Gaming': 'https://www.blueprintgaming.com',
    NetEnt: 'https://www.netent.com',
    'Ruby Play': 'https://www.rubyplay.com',
    Ainsworth: 'https://www.ainsworth.com.au',
    'Inspired Gaming': 'https://www.inseinc.com',
    'Red Tiger Gaming': 'https://www.redtiger.com',
    'Relax Gaming': 'https://www.relaxgaming.com',
    'Big Time Gaming': 'https://www.bigtimegaming.com',
    'Pragmatic Play': 'https://www.pragmaticplay.com',
    'Elk Studios': 'https://www.elkstudios.com',
    'ELK Studios': 'https://www.elkstudios.com',
    'Nolimit City': 'https://www.nolimitcity.com',
    'NoLimit City': 'https://www.nolimitcity.com',
    'Design Works Gaming': 'https://www.designworksgaming.com',
    'White Hat Studios': 'https://www.whitehatstudios.com',
    'Reel Play': 'https://www.reelplay.com',
    Spinberry: 'https://www.spinberry.com',
    'Red Rake Gaming': 'https://www.redrakegaming.com',

    // Aliases / extra entries from enrich_websearch.py PROVIDER_WEBSITES
    'Scientific Games': 'https://www.scientificgames.com',
    Microgaming: 'https://www.microgaming.co.uk',
    Yggdrasil: 'https://www.yggdrasilgaming.com',
    'Red Tiger': 'https://www.redtiger.com',
    'Push Gaming': 'https://www.pushgaming.com',
    'Fortune Factory Studios': 'https://www.playags.com',
    'Incredible Technologies': 'https://www.itsgames.com',
    Bluberi: 'https://www.bluberi.com',
    Zitro: 'https://www.zitrogames.com',
    'Aruze Gaming': 'https://www.aruzegaming.com',
};
